apiVersion: apps/v1
kind: Deployment
metadata:
  name: inframind-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-model
  template:
    metadata:
      labels:
        app: mock-model
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: fastapimodel
          image: inframind-model:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-service.monitoring.svc.cluster.local:9090"
            - name: QDRANT_URL
              value: "http://qdrant-service.monitoring.svc.cluster.local:6333"
            - name: QDRANT_COLLECTION
              value: "inframind_logs"
            - name: GROQ_API_KEY
              value: "GROQ_API_KEY"
            - name: INFRAMIND_NAMESPACE
              value: "monitoring"
            - name: INFRAMIND_DEPLOYMENT
              value: "inframind-model-deployment"
            - name: RESTART_COOLDOWN_SECONDS
              value: "60"
            - name: RESTART_MAX_PER_HOUR
              value: "6"
            - name: RESTART_MAX_RETRIES
              value: "2"
            - name: RESTART_WAIT_SECONDS
              value: "30"
          resources:
            requests:
              cpu: "500m"
              memory: "700Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"