apiVersion: v1
kind: ServiceAccount
metadata:
  name: inframind-restart-agent
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inframind-restart-role
  namespace: monitoring
rules:

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]


  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inframind-restart-binding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: inframind-restart-agent
    namespace: monitoring
roleRef:
  kind: Role
  name: inframind-restart-role
  apiGroup: rbac.authorization.k8s.io