apiVersion: v1
kind: Service
metadata:
  name: inframind-model-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: mock-model
  ports:
    - port: 8000
      targetPort: 8000
